spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 5MB
  thymeleaf:
    cache: false

  datasource:
    url: jdbc:mysql://localhost:3306/toutiao?useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123456

  http:
    encoding:
      charset: utf-8
      force: true
      enabled: true

  velocity:
    suffix: .html
    cache: false
    toolbox-config-location: toolbox.xml

  mail:
    host: smtp.qq.com
    username: xxx
    password: xxx
    protocol: smtp
    default-encoding: UTF-8

mybatis:
    mapper-locations: classpath:mybatis/**/*.xml
    config-location: classpath:mybatis-config.xml
    type-aliases-package: com.nowcoder.model
